### ISSUE TITLE
Exception on parse external content

### ISSUE THREAD

**Issue by wayne-zhang** [NickstaDB/SerializationDumper#24]
Exception in thread "main" java.lang.RuntimeException: Error: Unable to parse externalContent
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:865)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1510)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:989)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:939)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:886)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1510)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:989)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:939)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:886)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readContentElement(SerializationDumper.java:359)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:902)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1510)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:989)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:939)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:886)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1510)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:989)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:939)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:886)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1510)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:989)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:939)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:886)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readContentElement(SerializationDumper.java:359)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:902)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readContentElement(SerializationDumper.java:359)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:902)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1510)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:989)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:939)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:886)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:467)
        at nb.deser.SerializationDumper.readContentElement(SerializationDumper.java:359)
        at nb.deser.SerializationDumper.parseStream(SerializationDumper.java:331)
        at nb.deser.SerializationDumper.main(SerializationDumper.java:113)

**Comment by wayne-zhang** [comment]
[](url
[lfN6ovnDsHXPI_x75kwXle7uWqzQHC-Qb8jBpcE1kzGUwbOBPWEa!-400900651!484065004!1659914886648_1659928044238.zip](https://github.com/NickstaDB/SerializationDumper/files/9306998/lfN6ovnDsHXPI_x75kwXle7uWqzQHC-Qb8jBpcE1kzGUwbOBPWEa.-400900651.484065004.1659914886648_1659928044238.zip)
)

**Comment by wayne-zhang** [comment]
The serialization data is an HTTP session serialized in Weblogic, when the session size > 10MB. We use it to analysis large data in our application but failed to deserialize it with a tool we built.

This is a session in a JSF application, failed on deserialize Weld/CDI classes. Our tool can deserialize HTTP session dumped in (apache) Wicket web applications.
