### ISSUE TITLE
java.lang.RuntimeException: Error: Invalid classDesc reference (0x00 7e 02 ef

### ISSUE THREAD

**Issue by PhantomYdn** [NickstaDB/SerializationDumper#9]
Got the following error:

```
Exception in thread "main" java.lang.RuntimeException: Error: Invalid classDesc reference (0x00 7e 02 ef
        at nb.deser.SerializationDumper.readClassDesc(SerializationDumper.java:494)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:449)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1492)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:971)
        at nb.deser.SerializationDumper.readNewArray(SerializationDumper.java:1031)
        at nb.deser.SerializationDumper.readContentElement(SerializationDumper.java:355)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:875)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:455)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1492)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:971)
        at nb.deser.SerializationDumper.readClassDataField(SerializationDumper.java:921)
        at nb.deser.SerializationDumper.readClassData(SerializationDumper.java:859)
        at nb.deser.SerializationDumper.readNewObject(SerializationDumper.java:455)
        at nb.deser.SerializationDumper.readObjectField(SerializationDumper.java:1492)
        at nb.deser.SerializationDumper.readFieldValue(SerializationDumper.java:971)
```

**Comment by NickstaDB** [comment]
Hi @PhantomYdn, can you provide a sample input that leads to this exception?

**Comment by PhantomYdn** [comment]
It's pretty heavy: 80Mb+... 
Trying to fix in my fork. Btw, I have added support maven support. Will create PR once it's working OK for me.
Thank you for the lib!

**Comment by PhantomYdn** [comment]
As far as I can see, this assumption was incorrect: 
```java
//NB: Not clear whether a TC_PROXYCLASSDESC can be referenced in a classDesc element (e.g. object or array classDesc). Ignore this for now...
```
https://github.com/NickstaDB/SerializationDumper/blob/master/src/nb/deser/SerializationDumper.java#L582

**Comment by PhantomYdn** [comment]
Hello, @NickstaDB !
I have shared with you in DropBox the file which I'm trying to parse...
Please help if you can.

**Comment by NickstaDB** [comment]
Hi @PhantomYdn, thanks for sharing the sample data. You were right that there was an issue relating to TC_PROXYCLASSDESC and I've implemented fixes for those issues. Unfortunately it's not possible to dump the object that you're trying to dump.

The sample data contained an object of the class `com.orientechnologies.orient.core.record.impl.ODocument` which implements the `java.io.Externalizable` interface. When this interface is implemented, the `readExternal()` and `writeExternal()` methods are used to read and write arbitrary data in an arbitrary format. As such, it's impossible to generically read this data.

If you wanted you _could_ hack up the `readClassData()` method to detect the `com.orientechnologies.orient.core.record.impl.ODocument` class and mimic the `readExternal()` method of that class.

**Comment by PhantomYdn** [comment]
Thank you, @NickstaDB , for the fix!
Regarding `readExternal()` - is it possible at least print out the content in hex which dedicated to be consumed by this method? Or it consumes the whole input stream and it's not possible to findout boundaries for content of `readExternal()`?

**Comment by NickstaDB** [comment]
There's no generic way to identify the boundaries of data written by `writeExternal()`. One class might simply output an integer via `writeExternal()`, while another might output image dimensions followed by x*y integers to define the pixel colours of the image. It's completely arbitrary and Java's `ObjectOutputStream` doesn't insert a length field or mandate one so we can't read or skip over the data without implementing specific support for the class in question (`ODocument` in this case).
